[project]
name = "okapipy"
version = "0.1.0"
description = "Python OpenAPI Client Generator made OK"
authors = [{ name = "Francesco Faraone" }]
readme = { file = "README.md", content-type = "text/markdown" }
license = { file = "LICENSE" }
requires-python = ">=3.12,<4"
dependencies = [
    "datamodel-code-generator>=0.26,<1",
    "devtools>=0.12.2,<0.13.0",
    "jinja2>=3,<4",
    "openapi-spec-validator>=0.7,<1",
    "prance>=23.6,<26",
    "pydantic>=2.13.3,<3.0.0",
    "pyyaml>=6.0,<7",
    "rich>=13,<15",
    "spacy>=3.7,<4",
    "typer>=0.12,<1",
]

[dependency-groups]
dev = [
    "httpx>=0.27,<1",
    "ipython>=9.4.0,<10.0.0",
    "mypy>=1.17.1,<2.0.0",
    "pre-commit>=4.3.0,<5.0.0",
    "pytest>=8.4.2,<9.0.0",
    "pytest-asyncio>=1.2.0,<2.0.0",
    "pytest-cov>=7.0.0,<8.0.0",
    "pytest-mock>=3.15.1,<4.0.0",
    "pytest-randomly>=4.0.1,<5.0.0",
    "pytest-httpserver>=1.0,<2",
    "ruff>=0.15.11,<0.16.0",
    "types-pyyaml>=6.0.12.20250915,<7.0.0.0",
]

[tool.uv]
package = true
preview = true
add-bounds = "major"

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[tool.hatch.build.targets.wheel]
packages = ["src/okapipy"]

[project.scripts]
okapipy = "okapipy.app:main"


[tool.pytest.ini_options]
testpaths = "tests"
pythonpath = "."
addopts = "--cov=okapipy --cov-report=term-missing --cov-report=html --cov-report=xml"
cache_dir = ".cache/pytest"
log_cli = false
filterwarnings = [
    "ignore:Support for class-based `config` is deprecated:DeprecationWarning",
    "ignore:pkg_resources is deprecated as an API:DeprecationWarning",
]


[tool.coverage.run]
branch = true

[tool.ruff]
extend-exclude = [".vscode", ".devcontainer"]
output-format = "full"
cache-dir = "../.cache/ruff"

[tool.ruff.lint]
select = [
    "E",  # w errors
    "W",  # pycodestyle warnings
    "F",  # pyflakes
    "I",  # isort
    "B",  # flake8-bugbear
    "C4",  # flake8-comprehensions
    "UP",  # pyupgrade,
    "PT",  # flake8-pytest-style
    "T10",  # flake8-pytest-style
]
ignore = [
    "PT011", # pytest.raises({exception}) is too broad, set the match parameter or use a more specific exception
    "B008",  # do not perform function calls in argument defaults
    "B904",  # Within an `except` clause, raise exceptions with `raise ... from err` or `raise ... from None` to distinguish them from errors in exception handling
]

[tool.ruff.lint.isort]
known-first-party = ["okapipy"]

[tool.ruff.lint.pycodestyle]
max-line-length = 100

[tool.mypy]
warn_no_return = false
ignore_missing_imports = true
cache_dir = ".cache/mypy"
plugins = ["pydantic.mypy"]

[[tool.mypy.overrides]]
module = "okapipy.parser.*"
strict = true

[[tool.mypy.overrides]]
module = "okapipy.generator.*"
strict = true
