sonar.organization=ffaraone
sonar.projectKey=ffaraone_okapipy
sonar.projectName=okapipy

sonar.sources=src
sonar.tests=tests
sonar.python.version=3.12,3.13

sonar.python.coverage.reportPaths=coverage.xml
sonar.python.xunit.reportPath=junit.xml

sonar.exclusions=**/templates/**,dist/**,htmlcov/**,.cache/**,.spacy/**,assets/**,**/__pycache__/**
sonar.test.inclusions=tests/**
sonar.test.exclusions=tests/fixtures/**

sonar.coverage.exclusions=tests/**,**/templates/**,src/okapipy/cli/**,src/okapipy/app.py
