"""`datamodel-code-generator` integration tests."""

from __future__ import annotations

import importlib.util
import sys
from datetime import date, datetime
from pathlib import Path

import pytest
from pydantic import ValidationError

from okapipy.generator.models import _materialize_spec, emit_models

FIXTURE = Path(__file__).resolve().parent.parent / "fixtures" / "simple.yaml"


def test_emit_models_produces_pydantic_models() -> None:
    """`emit_models` returns Python source declaring the spec's schemas as Pydantic models."""
    source = emit_models(FIXTURE, model_templates_dir=None, python_version="3.13")

    assert "class Order" in source
    assert "class OrderList" in source
    assert "BaseModel" in source


def test_emit_models_prepends_banner() -> None:
    """A generator banner is prepended so users know the file is regenerable."""
    source = emit_models(FIXTURE, model_templates_dir=None, python_version="3.13")

    assert source.startswith("# Generated by okapipy via datamodel-code-generator.")


def test_generated_models_round_trip(tmp_path: Path) -> None:
    """Generated models actually validate input — write them out and `model_validate`.

    We import the file by path to avoid polluting `sys.modules` with a permanent
    `models` entry, and to avoid coupling the test to an `__init__.py`.
    """
    source = emit_models(FIXTURE, model_templates_dir=None, python_version="3.13")
    module_path = tmp_path / "generated_models.py"
    module_path.write_text(source, encoding="utf-8")

    spec = importlib.util.spec_from_file_location("test_generated_models", module_path)
    assert spec is not None
    assert spec.loader is not None
    module = importlib.util.module_from_spec(spec)
    sys.modules[spec.name] = module
    try:
        spec.loader.exec_module(module)
        order = module.Order.model_validate({"id": "42", "total": 9.99})
        assert order.id == "42"
        assert order.total == 9.99
        with pytest.raises(ValidationError):
            module.Order.model_validate({"id": 42, "total": "not a number"})
    finally:
        sys.modules.pop(spec.name, None)


def test_materialize_spec_handles_yaml_parsed_dates(tmp_path: Path) -> None:
    """Date / datetime values produced by PyYAML's safe_load survive JSON serialization.

    PyYAML auto-parses ISO 8601 literals into `datetime.date` / `datetime.datetime`
    instances. OpenAPI represents these as strings on the wire, so the spec
    materializer falls back to `isoformat()` rather than crashing with a
    TypeError. Without the fallback, any spec with a date default / example /
    metadata field would fail `okapipy spec generate`.
    """
    spec = {
        "openapi": "3.0.0",
        "info": {"title": "API", "version": "1.0.0"},
        "components": {
            "schemas": {
                "Event": {
                    "type": "object",
                    "properties": {
                        "scheduled_for": {
                            "type": "string",
                            "format": "date",
                            "default": date(2026, 5, 5),
                        },
                        "created_at": {
                            "type": "string",
                            "format": "date-time",
                            "example": datetime(2026, 5, 5, 12, 0, 0),
                        },
                    },
                }
            }
        },
        "paths": {},
    }

    target = _materialize_spec(spec, tmp_path)

    text = target.read_text(encoding="utf-8")
    assert '"2026-05-05"' in text
    assert '"2026-05-05T12:00:00"' in text


def test_model_templates_dir_is_honored(tmp_path: Path) -> None:
    """A user-supplied `model_templates_dir` is forwarded to dmcg's `custom_template_dir`.

    We override `BaseModel.jinja2` to inject a marker comment ahead of the class
    body, then assert the marker appears in the rendered output. The override is
    deliberately minimal — dmcg loads each subtemplate independently, so we only
    need to override the part we care about.
    """
    templates = tmp_path / "model-templates"
    pydantic_v2 = templates / "pydantic_v2"
    pydantic_v2.mkdir(parents=True)
    template_lines = [
        "# OKAPIPY_USER_TEMPLATE_MARKER",
        "class {{ class_name }}({{ base_class }}):",
        "{%- if not fields %}",
        "    pass",
        "{%- endif %}",
        "{%- for field in fields %}",
        "    {{ field.name }}: {{ field.type_hint }}"
        "{%- if field.field %} = {{ field.field }}{%- endif %}",
        "{%- endfor %}",
    ]
    (pydantic_v2 / "BaseModel.jinja2").write_text("\n".join(template_lines) + "\n")

    source = emit_models(
        FIXTURE,
        model_templates_dir=templates,
        python_version="3.13",
    )

    assert "OKAPIPY_USER_TEMPLATE_MARKER" in source
