"""`datamodel-code-generator` integration tests."""

from __future__ import annotations

import importlib.util
import sys
from pathlib import Path

import pytest
from pydantic import ValidationError

from okapipy.generator.models import emit_models

FIXTURE = Path(__file__).resolve().parent.parent / "fixtures" / "simple.yaml"


def test_emit_models_produces_pydantic_models() -> None:
    """`emit_models` returns Python source declaring the spec's schemas as Pydantic models."""
    source = emit_models(FIXTURE, model_templates_dir=None, python_version="3.13")

    assert "class Order" in source
    assert "class OrderList" in source
    assert "BaseModel" in source


def test_emit_models_prepends_banner() -> None:
    """A generator banner is prepended so users know the file is regenerable."""
    source = emit_models(FIXTURE, model_templates_dir=None, python_version="3.13")

    assert source.startswith("# Generated by okapipy via datamodel-code-generator.")


def test_generated_models_round_trip(tmp_path: Path) -> None:
    """Generated models actually validate input — write them out and `model_validate`.

    We import the file by path to avoid polluting `sys.modules` with a permanent
    `models` entry, and to avoid coupling the test to an `__init__.py`.
    """
    source = emit_models(FIXTURE, model_templates_dir=None, python_version="3.13")
    module_path = tmp_path / "generated_models.py"
    module_path.write_text(source, encoding="utf-8")

    spec = importlib.util.spec_from_file_location("test_generated_models", module_path)
    assert spec is not None
    assert spec.loader is not None
    module = importlib.util.module_from_spec(spec)
    sys.modules[spec.name] = module
    try:
        spec.loader.exec_module(module)
        order = module.Order.model_validate({"id": "42", "total": 9.99})
        assert order.id == "42"
        assert order.total == 9.99
        with pytest.raises(ValidationError):
            module.Order.model_validate({"id": 42, "total": "not a number"})
    finally:
        sys.modules.pop(spec.name, None)


def test_model_templates_dir_is_honored(tmp_path: Path) -> None:
    """A user-supplied `model_templates_dir` is forwarded to dmcg's `custom_template_dir`.

    We override `BaseModel.jinja2` to inject a marker comment ahead of the class
    body, then assert the marker appears in the rendered output. The override is
    deliberately minimal — dmcg loads each subtemplate independently, so we only
    need to override the part we care about.
    """
    templates = tmp_path / "model-templates"
    pydantic_v2 = templates / "pydantic_v2"
    pydantic_v2.mkdir(parents=True)
    template_lines = [
        "# OKAPIPY_USER_TEMPLATE_MARKER",
        "class {{ class_name }}({{ base_class }}):",
        "{%- if not fields %}",
        "    pass",
        "{%- endif %}",
        "{%- for field in fields %}",
        "    {{ field.name }}: {{ field.type_hint }}"
        "{%- if field.field %} = {{ field.field }}{%- endif %}",
        "{%- endfor %}",
    ]
    (pydantic_v2 / "BaseModel.jinja2").write_text("\n".join(template_lines) + "\n")

    source = emit_models(
        FIXTURE,
        model_templates_dir=templates,
        python_version="3.13",
    )

    assert "OKAPIPY_USER_TEMPLATE_MARKER" in source
