"""`datamodel-code-generator` integration.

Loads the OpenAPI spec, runs `flatten_inline_schemas` to hoist anonymous inline
schemas into `components.schemas` (so dmcg doesn't emit `By` / `By1` / `By2`
duplicates for structurally identical shapes), writes the preprocessed document
to a temp directory, invokes dmcg with `output_model_type=PydanticV2BaseModel`,
and reads the resulting `models.py` back into the virtual FS. The user-supplied
`model_templates_dir` is forwarded
to dmcg as `custom_template_dir`; when omitted, the bundled relaxed templates
under `templates/model/` are used: every field is forced optional (`| None`),
`extra="allow"` and `populate_by_name=True`, and the dmcg-generated `Field(...)`
call is preserved verbatim so spec-level constraints (`max_length`, `pattern`,
…) and metadata (`title`, `description`, `examples`) survive. When a field has
an alias from `snake_case_field=True`, the bare `alias=` kwarg is rewritten to
`validation_alias=AliasChoices(snake, original), serialization_alias=original`
so payloads can be sent or received under either name.
"""

from __future__ import annotations

import ast
import json
import subprocess
from datetime import date, datetime
from pathlib import Path
from tempfile import TemporaryDirectory
from typing import Any

from datamodel_code_generator import (  # type: ignore[attr-defined]
    DataModelType,
    InputFileType,
    PythonVersion,
)
from datamodel_code_generator import generate as dmcg_generate
from datamodel_code_generator.format import Formatter

from okapipy.generator.errors import GenerationError
from okapipy.parser.inline_schemas import flatten_inline_schemas
from okapipy.parser.loader import load_spec

DEFAULT_MODEL_TEMPLATES_DIR = Path(__file__).parent / "templates" / "model"

BANNER = (
    "# Generated by okapipy via datamodel-code-generator. Edit freely.\n"
    "# Regenerating overwrites this file.\n"
    "\n"
)


def emit_models(
    raw_spec: dict[str, Any] | str | Path,
    model_templates_dir: Path | None,
    python_version: str,
) -> str:
    """Render `models.py` content from `raw_spec`.

    Returns the rendered Python source (banner-prefixed). The caller places it
    into the virtual FS under `<package>/models.py`.

    Args:
        raw_spec: original OpenAPI document — a path to a file/URL, or an already
            loaded dict. Forwarded to dmcg's `input_` argument.
        model_templates_dir: directory of dmcg Jinja templates that override the
            built-in ones; passed straight through to `custom_template_dir`. When
            `None`, the bundled relaxed templates under `templates/model/` are used.
        python_version: target Python version, e.g. `"3.13"`. Maps to dmcg's
            `target_python_version` enum.
    """
    py_version = _python_version(python_version)
    templates_dir = (
        model_templates_dir
        if model_templates_dir is not None
        else DEFAULT_MODEL_TEMPLATES_DIR
    )
    with TemporaryDirectory() as tmp_str:
        tmp = Path(tmp_str)
        spec_path = _materialize_spec(raw_spec, tmp)
        out_path = tmp / "models.py"
        try:
            dmcg_generate(
                input_=spec_path,
                input_file_type=InputFileType.OpenAPI,
                output=out_path,
                output_model_type=DataModelType.PydanticV2BaseModel,
                target_python_version=py_version,
                use_double_quotes=True,
                use_union_operator=True,
                use_generic_container_types=True,
                field_constraints=True,
                allow_extra_fields=True,
                force_optional_for_required_fields=True,
                snake_case_field=True,
                custom_template_dir=templates_dir,
                additional_imports=[
                    "pydantic.ConfigDict",
                    "pydantic.AliasChoices",
                    "pydantic.Field",
                ],
                disable_timestamp=True,
                formatters=[Formatter.RUFF_FORMAT, Formatter.RUFF_CHECK],
            )
        except Exception as exc:  # dmcg surfaces a wide error set
            raise GenerationError(f"datamodel-code-generator failed: {exc}") from exc
        return BANNER + _polish(out_path.read_text(encoding="utf-8"))


def public_names(source: str) -> set[str]:
    """Return the set of top-level identifiers defined in `source`.

    Used by the walker to filter `from ..models import ...` lines so they only
    reference symbols dmcg actually emitted. dmcg sometimes drops or aliases
    schemas (primitive aliases, empty objects, schemas resolving to `Any`),
    so a parser-recovered ref name like `Data` may not exist in the output.
    Includes class names, simple `Name = ...` assignments, and `Name: ... = ...`
    annotated assignments — covers both `class Foo(BaseModel)` and dmcg's
    `Foo = list[Bar]` / `Foo: TypeAlias = ...` outputs.
    """
    try:
        tree = ast.parse(source)
    except SyntaxError:
        return set()
    names: set[str] = set()
    for node in tree.body:
        if isinstance(node, ast.ClassDef):
            names.add(node.name)
        elif isinstance(node, ast.Assign):
            for target in node.targets:
                if isinstance(target, ast.Name):
                    names.add(target.id)
        elif isinstance(node, ast.AnnAssign) and isinstance(node.target, ast.Name):
            names.add(node.target.id)
    return names


def _polish(source: str) -> str:
    """Run `ruff check --fix --select I` then `ruff format` on `source`.

    dmcg's own formatter doesn't apply isort; the generated tree's ruff config
    enforces it. Post-processing here keeps `models.py` linter-clean against the
    same rules as the rest of the generated package.
    """
    fixed = _run_ruff(
        ["check", "--fix", "--select", "I", "--stdin-filename", "models.py", "-"],
        source,
    )
    return _run_ruff(["format", "--stdin-filename", "models.py", "-"], fixed)


def _run_ruff(args: list[str], stdin: str) -> str:
    """Invoke ruff with `args`, feeding `stdin`, returning stdout. Raise on failure."""
    try:
        result = subprocess.run(
            ["ruff", *args],
            input=stdin,
            capture_output=True,
            text=True,
            check=False,
        )
    except FileNotFoundError as exc:
        raise GenerationError("ruff is not installed") from exc
    if result.returncode != 0:
        raise GenerationError(f"ruff {args[0]} rejected dmcg output:\n{result.stderr}")
    return result.stdout


def _materialize_spec(raw_spec: dict[str, Any] | str | Path, tmp: Path) -> Path:
    """Load `raw_spec`, run inline-schema flattening, and write the result to `tmp`.

    Always returns a path under `tmp` so dmcg consumes the preprocessed spec rather
    than the original. URL-string sources are loaded via `okapipy.parser.loader` so
    we can mutate them in-memory before handing off.
    """
    spec = _load_to_dict(raw_spec)
    spec = flatten_inline_schemas(spec)
    target = tmp / "openapi.json"
    target.write_text(json.dumps(spec, default=_json_default), encoding="utf-8")
    return target


def _json_default(value: object) -> str:
    """Coerce non-JSON-native scalars (notably YAML-parsed dates) to ISO strings.

    PyYAML's safe_load auto-parses ISO 8601 date / datetime literals into Python
    `datetime.date` / `datetime.datetime` instances, which `json.dumps` rejects.
    OpenAPI represents these values as strings on the wire, so emitting their
    `isoformat()` is the round-trip-safe fallback.
    """
    if isinstance(value, datetime):
        return value.isoformat()
    if isinstance(value, date):
        return value.isoformat()
    raise TypeError(
        f"OpenAPI spec contains a value of type {type(value).__name__} "
        "that cannot be encoded as JSON"
    )


def _load_to_dict(raw_spec: dict[str, Any] | str | Path) -> dict[str, Any]:
    """Coerce a path / URL / dict / raw-JSON-string source to an in-memory dict."""
    if isinstance(raw_spec, dict):
        return raw_spec
    if isinstance(raw_spec, Path):
        return load_spec(raw_spec)
    if raw_spec.startswith(("http://", "https://")):
        return load_spec(raw_spec)
    local = Path(raw_spec)
    if local.exists():
        return load_spec(local)
    parsed: dict[str, Any] = json.loads(raw_spec)
    return parsed


def _python_version(version: str) -> PythonVersion:
    """Translate `"3.13"` style strings to dmcg's `PythonVersion` enum."""
    table = {
        "3.10": PythonVersion.PY_310,
        "3.11": PythonVersion.PY_311,
        "3.12": PythonVersion.PY_312,
        "3.13": PythonVersion.PY_313,
    }
    if version not in table:
        raise GenerationError(f"unsupported python_version for dmcg: {version!r}")
    return table[version]
