"""`datamodel-code-generator` integration.

Writes the raw OpenAPI spec to a temp directory, invokes dmcg with
`output_model_type=PydanticV2BaseModel`, and reads the resulting `models.py`
back into the virtual FS. The user-supplied `model_templates_dir` is forwarded
to dmcg as `custom_template_dir`.
"""

from __future__ import annotations

import json
import subprocess
from pathlib import Path
from tempfile import TemporaryDirectory
from typing import Any

from datamodel_code_generator import (  # type: ignore[attr-defined]
    DataModelType,
    InputFileType,
    PythonVersion,
)
from datamodel_code_generator import generate as dmcg_generate
from datamodel_code_generator.format import Formatter

from okapipy.generator.errors import GenerationError

BANNER = (
    "# Generated by okapipy via datamodel-code-generator. Edit freely.\n"
    "# Regenerating overwrites this file.\n"
    "\n"
)


def emit_models(
    raw_spec: dict[str, Any] | str | Path,
    model_templates_dir: Path | None,
    python_version: str,
) -> str:
    """Render `models.py` content from `raw_spec`.

    Returns the rendered Python source (banner-prefixed). The caller places it
    into the virtual FS under `<package>/models.py`.

    Args:
        raw_spec: original OpenAPI document — a path to a file/URL, or an already
            loaded dict. Forwarded to dmcg's `input_` argument.
        model_templates_dir: directory of dmcg Jinja templates that override the
            built-in ones; passed straight through to `custom_template_dir`.
        python_version: target Python version, e.g. `"3.13"`. Maps to dmcg's
            `target_python_version` enum.
    """
    py_version = _python_version(python_version)
    with TemporaryDirectory() as tmp_str:
        tmp = Path(tmp_str)
        spec_path = _materialize_spec(raw_spec, tmp)
        out_path = tmp / "models.py"
        try:
            dmcg_generate(
                input_=spec_path,
                input_file_type=InputFileType.OpenAPI,
                output=out_path,
                output_model_type=DataModelType.PydanticV2BaseModel,
                target_python_version=py_version,
                use_standard_collections=True,
                use_union_operator=True,
                custom_template_dir=model_templates_dir,
                formatters=[Formatter.RUFF_FORMAT, Formatter.RUFF_CHECK],
            )
        except Exception as exc:  # dmcg surfaces a wide error set
            raise GenerationError(f"datamodel-code-generator failed: {exc}") from exc
        return BANNER + _polish(out_path.read_text(encoding="utf-8"))


def _polish(source: str) -> str:
    """Run `ruff check --fix --select I` then `ruff format` on `source`.

    dmcg's own formatter doesn't apply isort; the generated tree's ruff config
    enforces it. Post-processing here keeps `models.py` linter-clean against the
    same rules as the rest of the generated package.
    """
    fixed = _run_ruff(
        ["check", "--fix", "--select", "I", "--stdin-filename", "models.py", "-"],
        source,
    )
    return _run_ruff(["format", "--stdin-filename", "models.py", "-"], fixed)


def _run_ruff(args: list[str], stdin: str) -> str:
    """Invoke ruff with `args`, feeding `stdin`, returning stdout. Raise on failure."""
    try:
        result = subprocess.run(
            ["ruff", *args],
            input=stdin,
            capture_output=True,
            text=True,
            check=False,
        )
    except FileNotFoundError as exc:
        raise GenerationError("ruff is not installed") from exc
    if result.returncode != 0:
        raise GenerationError(
            f"ruff {args[0]} rejected dmcg output:\n{result.stderr}"
        )
    return result.stdout


def _materialize_spec(raw_spec: dict[str, Any] | str | Path, tmp: Path) -> Path:
    """Return a filesystem path for `raw_spec`, writing it to `tmp` if needed."""
    if isinstance(raw_spec, Path):
        return raw_spec
    if isinstance(raw_spec, str):
        # CLI passes the source argument verbatim — could be a URL or a path. dmcg
        # handles URLs natively when given as a path-like, so a `Path(...)` is fine
        # even for URL strings as long as we don't try to read locally.
        if raw_spec.startswith(("http://", "https://")):
            return Path(raw_spec)
        local = Path(raw_spec)
        if local.exists():
            return local
        # Fallback: treat the string as JSON content.
        target = tmp / "openapi.json"
        target.write_text(raw_spec, encoding="utf-8")
        return target
    target = tmp / "openapi.json"
    target.write_text(json.dumps(raw_spec), encoding="utf-8")
    return target


def _python_version(version: str) -> PythonVersion:
    """Translate `"3.13"` style strings to dmcg's `PythonVersion` enum."""
    table = {
        "3.10": PythonVersion.PY_310,
        "3.11": PythonVersion.PY_311,
        "3.12": PythonVersion.PY_312,
        "3.13": PythonVersion.PY_313,
    }
    if version not in table:
        raise GenerationError(f"unsupported python_version for dmcg: {version!r}")
    return table[version]
