"""Copy the vendored runtime into the virtual FS.

Walks `okapipy.generator.runtime.*.py` source files and writes each one into
`<package_path>/<filename>` with a generator banner prepended. Files are not
templated — they're verbatim Python — and are not run through `ruff format`
(they're already formatted at source). The generated `__init__.py` is
constructed here and then run through ruff (format + isort fix) so it conforms
to the same lint rules as the rest of the generated tree.
"""

from __future__ import annotations

import subprocess
from pathlib import Path

from okapipy.generator import runtime as runtime_pkg
from okapipy.generator.errors import GenerationError

BANNER = (
    "# Generated by okapipy; vendored from okapipy.generator.runtime.\n"
    "# Edit freely — okapipy never reads this file back.\n"
    "\n"
)

# Files in the runtime package to vendor. `__init__.py` is rebuilt per generation
# because its imports reference siblings that may not all be present in v0.
RUNTIME_FILES = (
    "types.py",
    "exceptions.py",
    "filters.py",
    "sort.py",
    "strategies.py",
    "transport.py",
)


def emit_runtime(
    package_path: str,
    client_class: str,
    extra_imports: list[str] | None = None,
    extra_public_names: list[str] | None = None,
) -> dict[str, str]:
    """Return a virtual-FS dict of the runtime files placed under `package_path`.

    `extra_imports` / `extra_public_names` (from `walk.emit_root_init_extension`)
    are merged into the generated `__init__.py` so top-level namespace and
    collection classes are re-exported alongside the runtime types.
    """
    runtime_root = Path(runtime_pkg.__file__).parent
    out: dict[str, str] = {}
    for name in RUNTIME_FILES:
        source = (runtime_root / name).read_text(encoding="utf-8")
        out[f"src/{package_path}/base/{name}"] = BANNER + source
    init_text = _runtime_init(
        client_class, extra_imports or [], extra_public_names or []
    )
    out[f"src/{package_path}/base/__init__.py"] = _polish(init_text)
    return out


def _polish(source: str) -> str:
    """Run isort fix + ruff format on the generated `__init__.py`."""
    fixed = _run_ruff(
        ["check", "--fix", "--select", "I", "--stdin-filename", "__init__.py", "-"],
        source,
    )
    return _run_ruff(["format", "--stdin-filename", "__init__.py", "-"], fixed)


def _run_ruff(args: list[str], stdin: str) -> str:
    """Invoke `ruff` with `args`, feeding `stdin`, returning stdout."""
    try:
        result = subprocess.run(
            ["ruff", *args],
            input=stdin,
            capture_output=True,
            text=True,
            check=False,
        )
    except FileNotFoundError as exc:
        raise GenerationError("ruff is not installed") from exc
    if result.returncode != 0:
        raise GenerationError(
            f"ruff {args[0]} rejected runtime __init__.py:\n{result.stderr}"
        )
    return result.stdout


RUNTIME_PUBLIC_NAMES: tuple[str, ...] = (
    "UNSET",
    "AndFilter",
    "ApiError",
    "AsyncRetryTransport",
    "ClientError",
    "CommaSignedSort",
    "ConfigurationError",
    "CursorPagination",
    "Filter",
    "FilterEncoding",
    "FilterStrategy",
    "JsonApiSort",
    "JsonFilterStrategy",
    "KeyDirectionSort",
    "KeyOpValueFilter",
    "KeyValueFilter",
    "LinkHeaderPagination",
    "NotFilter",
    "LimitOffsetPagination",
    "OrFilter",
    "PageNumberPagination",
    "PaginationStrategy",
    "RequestOptions",
    "ResponseValidationError",
    "RetryPolicy",
    "RetryTransport",
    "Search",
    "SearchFilterStrategy",
    "ServerError",
    "Sort",
    "SortEncoding",
    "SortStrategy",
    "Unset",
    "UnsupportedFilterError",
    "UnsupportedFilterKeyError",
    "UnsupportedPaginationError",
    "UnsupportedSortError",
    "UnsupportedSortFieldError",
)


def _runtime_init(
    client_class: str,
    extra_imports: list[str],
    extra_public_names: list[str],
) -> str:
    """Return the generated package's `__init__.py` re-exporting the public API.

    Replaces the empty stub from the project skeleton. Re-exports the runtime
    primitives plus the sync (`<client_class>Base`) and async
    (`Async<client_class>Base`) client classes from `client.py`, and any
    top-level namespace / collection `*Base` classes the walker provides via
    `extra_imports` / `extra_public_names`.
    """
    all_names = (
        *RUNTIME_PUBLIC_NAMES,
        f"{client_class}Base",
        f"Async{client_class}Base",
        *extra_public_names,
    )
    all_block = ",\n    ".join(f'"{name}"' for name in all_names)
    extras_block = ("\n" + "\n".join(extra_imports)) if extra_imports else ""
    return (
        BANNER
        + '"""Generated package — public surface re-exports."""\n'
        + "\n"
        + "from __future__ import annotations\n"
        + "\n"
        + "from .exceptions import (\n"
        + "    ApiError,\n"
        + "    ClientError,\n"
        + "    ConfigurationError,\n"
        + "    ResponseValidationError,\n"
        + "    ServerError,\n"
        + "    UnsupportedFilterError,\n"
        + "    UnsupportedFilterKeyError,\n"
        + "    UnsupportedPaginationError,\n"
        + "    UnsupportedSortError,\n"
        + "    UnsupportedSortFieldError,\n"
        + ")\n"
        + "from .filters import AndFilter, Filter, NotFilter, OrFilter, Search\n"
        + "from .sort import Sort\n"
        + "from .strategies import (\n"
        + "    CommaSignedSort,\n"
        + "    CursorPagination,\n"
        + "    FilterEncoding,\n"
        + "    FilterStrategy,\n"
        + "    JsonApiSort,\n"
        + "    JsonFilterStrategy,\n"
        + "    KeyDirectionSort,\n"
        + "    KeyOpValueFilter,\n"
        + "    KeyValueFilter,\n"
        + "    LinkHeaderPagination,\n"
        + "    LimitOffsetPagination,\n"
        + "    PageNumberPagination,\n"
        + "    PaginationStrategy,\n"
        + "    SearchFilterStrategy,\n"
        + "    SortEncoding,\n"
        + "    SortStrategy,\n"
        + ")\n"
        + "from .transport import AsyncRetryTransport, RetryPolicy, RetryTransport\n"
        + "from .types import UNSET, RequestOptions, Unset\n"
        + f"from .client import {client_class}Base, Async{client_class}Base"
        + extras_block
        + "\n\n"
        + "__all__ = [\n"
        + f"    {all_block},\n"
        + "]\n"
    )
